### ISSUE TITLE
Calculate number of each applicant field such as Gender, Age, etc. For every new applicant, number in database will increase by one. This will happen in the middleware.

### ISSUE THREAD

**Issue by ghost** [CMU-313/fall22-hw3-team-troubleshooters#1]
After adding the document data to the database, we want to do some count and average functions called on the database. 

We will be updating some java files in the rest layer probably. 

**Estimated Effort**: 3 hours for coding and 1.5 hours for implementing tests.
It is similar to something we have done before, and we multiplied by 3 to overestimate time. Testing if the function works doesn't seem to be too hard.
**Dependencies**: This task depends on the database to be finished. This task should be tackled first before rest layer and implementing the dashboard html.
**Acceptance Criteria**: This is done when tests pass.

**Comment by Charlyjcmu** [comment]
This issue was closed by the merging of #12. It helped calculate average statistics in the middleware which was prepared to be sent to the front end.
